targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/**.dart
            - lib/pages/**.dart
            - lib/app_router.dart
      json_serializable:
        generate_for:
          include:
            - lib/models/**.dart
        options:
          any_map: true
          explicit_to_json: true