name: money_hacker
description: お金の解像度を上げていく計算機

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.1.1
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  firebase_analytics: ^9.1.0

  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  reactive_forms: ^11.0.1

  rxdart: ^0.27.0

  json_annotation: ^4.0.1
  freezed_annotation: ^1.1.0

  # 小物
  enum_to_string: ^2.0.1
  quiver: ^3.0.1
  uuid: ^3.0.4
  collection: ^1.15.0
  pattern_formatter: ^2.0.0
  intl: any
  uri: ^1.0.0

  cupertino_icons: ^1.0.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  freezed: ^1.1.1
  build_runner: ^2.0.3
  pedantic: ^1.11.0

analyzer:
  rules:
    ignore: non_constant_identifier_names
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
