name: Production Deploy

on:
  push:
    branches:
      - master

env:
  FIREBASE_PROJECT_PATH: ./firebase
  PROCJECT_SOURCE_PATH: ./flutter
  # RESOURCE_DIR: functions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --web-renderer html
        working-directory: ${{ env.PROCJECT_SOURCE_PATH }}
      # - name: Install dependencies
      #   run: npm install
      #   working-directory: ${{ env.FIREBASE_PROJECT_PATH }}/${{ env.RESOURCE_DIR }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONEY_HACKER }}"
          projectId: money-hacker
